# ANSWER-1 _PART-1_

In [1]:
import numpy as np

arr = np.array(range(1, 21, 3))
print(arr)

[ 1  4  7 10 13 16 19]


# ANSWER-2


In [2]:
arr = np.random.rand(3)
print(arr)

[0.65725608 0.77725385 0.60408207]


# ANSWER-3

In [3]:
import numpy as np

arr = np.array([[10, 20, 45], [30, 12, 16], [42, 17, 56]])

# Slice the 2D array to get the first two rows
first_two_rows = arr[:2, :]
print(first_two_rows)

# Slice the 2D array to get the last two rows
last_two_rows = arr[-2:, :]
print(last_two_rows)

[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


# ANSWER-4

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack the arrays vertically
vertically_stacked = np.vstack((arr1, arr2))
print(vertically_stacked)

# Stack the arrays horizontally
horizontally_stacked = np.hstack((arr1, arr2))
print(horizontally_stacked)

# Split the arrays
split_arrays = np.split(horizontally_stacked, 2)
print(split_arrays)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[array([[1, 2, 5, 6]]), array([[3, 4, 7, 8]])]


# ANSWER-5

In [5]:
X = np.array([[5, 7, 2], [4, 5, 6], [7, 4, 2]])
Y = np.array([[4, 2], [6, 2], [4, 2]])

# Multiply the matrices
result = np.matmul(X, Y)
print(result)

[[70 28]
 [70 30]
 [60 26]]


# ANSWER-6


In [6]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Find the shape and number of dimensions of vector x
shape_x = x.shape
dim_x = x.ndim
print("Shape of x:", shape_x)
print("Number of dimensions of x:", dim_x)

# Reshape vector x to a matrix of size (3, 1)
reshaped_x = x.reshape((3, 1))
dim_reshaped_x = reshaped_x.ndim
print("Reshaped x:", reshaped_x)
print("Number of dimensions of reshaped x:", dim_reshaped_x)

# Reshape y to a matrix of size (3, 1)
reshaped_y = y.reshape((3, 1))
dim_reshaped_y = reshaped_y.ndim
print("Reshaped y:", reshaped_y)
print("Number of dimensions of reshaped y:", dim_reshaped_y)

Shape of x: (3,)
Number of dimensions of x: 1
Reshaped x: [[ 2]
 [-1]
 [-8]]
Number of dimensions of reshaped x: 2
Reshaped y: [[ 3]
 [ 1]
 [-2]]
Number of dimensions of reshaped y: 2


# ANSWER-7


In [7]:

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([10, 20, 30])

# Broadcasting subtraction
subtracted = a - b
print(subtracted)

# Broadcasting multiplication
multiplied = a * b
print(multiplied)

[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]
[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


# ANSWER-1 _PART-2_

In [19]:
A = np.array([[4, 1, -2], [2, -3, 2], [1, 2, 3]]) 
b = np.array([10, -4, 6])

matrix = np.column_stack((A, b)) 
rank = np.linalg.matrix_rank(matrix)

x, y, z = np.linalg.solve(A, b)

print("coefficient matrix is :",rank)





coefficient matrix is : 3


### (A-1)This system has a unique solution, because  matrix is equal to the rank of the coefficient matrix.
### Therefore, the system can be solved using NumPy functions.

# ANSWER-2 

In [20]:
A2 = np.array([[2, -1, 3, 4], [4, -2, 6, 8], [3, 1, -2, 2], [1, 3, -4, 1]]) 
b2 = np.array([10, 20, 3, -1])

matrix_ = np.column_stack((A2, b2)) 
rank_ = np.linalg.matrix_rank(matrix_)

print("coefficient matrix is :",rank_)



coefficient matrix is : 3


### (A-2)In this case, the rank of the augmented matrix is 3, but the number of variables is 4. indicating that the system has infinitely many solutions.
### Therefore, the system cannot be solved using NumPy functions.